# Generated by Django 2.1.7 on 2019-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
