# Generated by Django 2.1.7 on 2019-03-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydata', '0002_auto_20190317_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posittion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='posittion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familydata.Posittion'),
        ),
    ]
