# Generated by Django 2.1.7 on 2019-03-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydata', '0004_familyapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='familyapply',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydata.Package'),
        ),
    ]
